webtalk_init -webtalk_dir C:/Data/Naist/Research/Software/QEA_Internal_BRAM/fast-psr/hardware_sim/xsim.dir/tb_snapshot_TB_QEA_7_qubits_quanvolutional_18/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Mar 11 16:21:35 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "db8277f6-4850-454a-827b-bed21739d886" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "fd2ace8a-78d6-45c9-a8f5-c688c2c1ba2e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "14" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 5700G with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3793 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "33.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runtime -value "19948 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.09_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "15164_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3244037605 -regid "" -xml C:/Data/Naist/Research/Software/QEA_Internal_BRAM/fast-psr/hardware_sim/xsim.dir/tb_snapshot_TB_QEA_7_qubits_quanvolutional_18/webtalk/usage_statistics_ext_xsim.xml -html C:/Data/Naist/Research/Software/QEA_Internal_BRAM/fast-psr/hardware_sim/xsim.dir/tb_snapshot_TB_QEA_7_qubits_quanvolutional_18/webtalk/usage_statistics_ext_xsim.html -wdm C:/Data/Naist/Research/Software/QEA_Internal_BRAM/fast-psr/hardware_sim/xsim.dir/tb_snapshot_TB_QEA_7_qubits_quanvolutional_18/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
